security:
    encoders\Sweb\BlogBundle\Entity\User:
      algorithms: bcrypt

    role_hierachy:
      ROLE_ADMIN: ROLE_USER
      ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
          entity: { class: Sweb\BlogBundle\Entity:User, propety: nick }

    firewalls:
        admin_area:
           pattern:    ^/admin
           http_basic: ~

          access_control:
              - { path: ^/admin, roles: ROLE_ADMIN }
